### ISSUE TITLE
Anfrage zur Benutzung

### ISSUE THREAD

**Issue by umgefahren** [ChuangSheep/bwinf2020#1]
Hallo,
ich habe wie du an der zweiten Runde BWINF teilgenommen. Außerdem muss ich darüber einen Vortrag halten. Deine Analysen, die erschreckend fortgeschrittenes OR (woher kannst du das?) enthalten, sind besser als meine, genauso wie deine Lösungsmethode. Darf ich deine Arbeit für die Präsentation verwenden? Ich werde dich selbstverständlich nennen.

**Comment by ChuangSheep** [comment]
Guten Tag,
sehr gerne darfst du alle Inhalte aus diesem Repository unter den [Lizenzbedingungen](https://github.com/ChuangSheep/bwinf2020/blob/658078ee23a9bfb7d238d9f04e2a1022a5284bc4/LICENSE) verwenden. Das heißt also, dass mich genannt werden muss und falls du was auf meinem Code aufbaust und veröffentlichen möchtest, musst du das unter derselben Lizenz machen. 

Mit "erschreckend fortgeschritten" meinst du die Aufgabe 1 oder 2? Ich bin auf den Algorithmus von Aufgabe 1 gekommen, als ich an das Knapsack Problem dachte. Es ist ähnlich, denn beide der Probleme sind All-Or-Nothing. Bei dieser Aufgabe, entweder nimmt man den Anbieter für das ganze Zeitintervall und gibt ihm alle Plätze, die er braucht, oder doch nicht. Da kann man nicht sagen, dass man einem Anbieter nur zwischen 8 bis 10 Uhr den Platz anbietet, während er vielleicht 8 bis 13 Uhr dabei sein möchte. Da kommt also das [0-1-ILP](https://en.wikipedia.org/wiki/Integer_programming) ins Spiel und Weiteres findest du dann in der Dokumentation. Es gibt auch [einen guten Artikel](https://brilliant.org/wiki/linear-programming/) über normales LP auf Brilliant. Wenn man das versteht, ist einfach den Algorithmus zu ILP anzupassen. 

Ich möchte aber darauf hinweisen, dass die Lösung möglicherweise nicht (komplett) richtig ist. Da dort nur für einzelne Intervalle gedacht wird, weiß ich eigentlich nicht, ob man in der Realität auch so eine Zuordnung finden kann, dass man die Verkäufer nicht irgendwann doch verschieben muss (Vgl. mein [Forum-Beitrag](https://www.einstieg-informatik.de/community/forums/topic/765/39-2-allgemein-austausch-uber-losungen)). Gegenbeispiele habe ich bisher allerdings nicht gefunden. 

Den Algorithmus von Aufgabe 2 finde ich recht einfach, scheint auch für die anderen, die ihre Lösungen veröffentlicht haben, zu sein, da fast alle denselben Lösungsweg gewählt haben. Für weitere Frage stehe ich aber gerne zur Verfügung.

**Comment by umgefahren** [comment]
Guten Tag,
ich habe nicht vor das zu veröffentlichen, aber wenn bin ich mit GPL-v3 und dem starken Copyleft vertraut.

Ja ich meine Aufgabe 1. Vielen Dank für die Links. Werde ich auf jeden Fall mal anschauen. Mir wurde nur gesagt, dass sei OR aus dem 3. Semester Wirtschaftsingenieurwesen. Mir war einfach nicht bewusst wie verdammt hoch das Niveau beim BWINF ist.

Ja ich hab das im Forum auch gesehen. Wenn dein Verfahren korrekt arbeitet, müsste man doch eine Karte zeichnen können, wo jeder Stand eingezeichnet ist. Das könnte aber schwierig werden, da dein Verfahren ja keine Positionen für die Stände ausgibt.

Aufgabe 2 habe ich genauso gelöst.

Ehrlich gesagt verstehe ich die Einträge von R_10 bis R_{n + 9} in deinem Simplex-Tableau nicht. Kannst du vielleicht erklären für was die sind? Wenn ich das richtig sehe ist das ja für die Bedingung x <= 1, warum aber benötig man da nochmal die Schlupfvariablen und vor allem x_{n - 1}?

**Comment by ChuangSheep** [comment]
Ich habe es nochmal angeschaut. Ich glaube ich habe einen Fehler gemacht, da sollte in {R_10} nur für die Spalte {x_0} und {s_10} 1 stehen. Danke für den Hinweis, ich werde es zeitnah korrigieren. 

Und nochmal zu R_10 bis R_{n+9}: Ganau, diese Zeile sind für die Bedingung x_i <= 1. Bei der Simplex-Methode muss für jede Ungleichung eine Schlupfvariable eingesetzt werden. Da x_i <= 1 auch eine Ungleichung ist, gilt das ebenfalls. 

Wie du vielleicht auch siehst, gibt es dadurch viele zusätzliche Ungleichungen. Das hätte man vermeiden können, wie ich auch in der Dokumentation erwähnt habe. Da ich da keine besondere zeitliche Vorteile sehe, habe ich es nicht abgegeben. Das habe ich tatsächlich implementiert. Falls du Interesse hast, kann ich dir den Code schicken.

**Comment by ChuangSheep** [comment]
Da es keine weitere Frage mehr zu geben scheint, schließe ich nun das Issue. Zur weiteren Frage könntest du gerne das wieder öffnen.
